### ISSUE TITLE
.sql file

### ISSUE THREAD

**Issue by TheYahya** [mbpcoder/database-schema#1]
Hi, 
Nice work here @mbpcoder,
I just have a recommendation; If there was a `.sql` file for each DB, So everyone can imported in mysql and have real look at, maybe was better.

thank you.

**Comment by mbpcoder** [comment]
Thanks @TheYahya 
It is a good idea. I will do it

**Comment by mbpcoder** [comment]
@TheYahya 
I added the SQL file
09d2352ae9db088357d55b78a61e1bb574d5d286
